In [ ]:
import numpy as np  #as - alias
print(np.__version__)


1.19.5


In [ ]:
ar1 = np.array([1,2,3,4,5])  #1-D
print(type(ar1))

<class 'numpy.ndarray'>


In [ ]:
#2-D

ar1 = np.array([[1,2,3], [4,5,6]])
print(ar1.ndim)

2


In [ ]:
arr = np.array([1,2,3,4])
print(arr[-1])

4


In [ ]:
#Slicing

arr = np.array([1,2,3,4,5,6,7])
print(arr[1:7:2])

[2 4 6]


In [ ]:
# Datatypes:

arr = np.array([1,2,3,4], dtype = 'i4')
print(arr.dtype)

int32


In [ ]:
#Conversion

arr = np.array([1,0,2])

newar1 = arr.astype(bool)

print(newar1)
print(newar1.dtype)

[ True False  True]
bool


In [ ]:
# diff b/w copy and view func in numpy
# copy - new array is created in a new location, view means viewing in same location


arr = np.array([1,2,3,4])
x = arr.copy()   # Copy
arr[0] = 6
print(arr)
print(x)

[6 2 3 4]
[1 2 3 4]


In [ ]:
arr = np.array([1,2,3,4])
x = arr.view()  # View
arr[0] = 6
print(arr)
print(x)


[6 2 3 4]
[6 2 3 4]


In [ ]:
#Shape
# in rows vs columns or elements in a tuple

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)



(2, 4)


In [ ]:
#Reshape 1D TO 3D

arr = np.array([1,2,3,4,5,6,7,8,9,10,12,13])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [12 13]]]


In [ ]:
#Iteration in Numpy
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
#nditer()

arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
#Joining arrays

ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

arr = np.stack((ar1,ar2),axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Split numpy arrays
# array_split()


arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,5)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
#Searching arrays
# where()

arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 1)
print(x)



(array([0, 2, 4, 6]),)


In [ ]:
#Sorting arrays
#ordered sequence
# sort()

arr =  np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [ ]:
# 2-D array sort

arr = np.array([[4,2,3],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#Filter Numpy Array

arr = np.array([12,131,41,52])
x = [True, False, True, False]
newar1 = arr[x]
print(newar1)

[12 41]


In [ ]:
#Random numbers in Numpy

from numpy import random
x = random.randint(100,size = (3,5))
print(x)

[[85 97 95 48 31]
 [31 73 82 47 31]
 [64 60  2 18 70]]
